### ISSUE TITLE
Disable Closing?

### ISSUE THREAD

**Issue by tomardern** [plainsheet/plainsheet#39]
Hi, 

Great library, looking forward to using it in production.

Is there a way to disable the ability to close the sheet? As in, the user can only drag it to the collapsed state?

Thanks,

**Comment by peter-byun** [comment]
Thank you, @tomardern, for reporting the issue! 
The library did not provide a way to implement such behavior, but I just released version 0.4.8 of `@plainsheet/react`, adding the new prop `preventClosing`, which exactly does what you kindly suggested.

[Here is the example](https://plainsheet-example-nextjs.vercel.app/mutable-props/prevent-closing), and [the API document](https://www.plainsheet.org/apis/react#behavior) will be updated shortly, too.

Thanks again for the brilliant suggestion!

**Comment by peter-byun** [comment]
Glad you liked it! Thanks.
